name: Mailcheck
author: D_mitar
category: Interface
tags: [input, suggest, email, string]
docs: https://github.com/DimitarChristoff/mailcheck#readme
demo: http://jsfiddle.net/dimitar/jSn3e/
current: 1